### ISSUE TITLE
[Bug]: Unexpected Application Error!

### ISSUE THREAD

**Issue by ViSTiE** [agoralabs-sh/kibisis-web-extension#293]
### Contact Details

simpty@live.de

### Version

1.18.1

### What browser are you seeing the problem on?

Edge

### Description

I want to sign a transaction. The wallet is called, but it is completely white, with no buttons, nothing. Just a white empty space.
When I click on the wallet icon in the browser, the wallet is shown, everything works. But when I want to connect the wallet with a website while it is open, the wallet shows:

Unexpected Application Error!
Cannot read properties of undefined (reading 'toString')
TypeError: Cannot read properties of undefined (reading 'toString')

### Steps To Reproduce

1. Open the wallet
2. While the wallet is open, connect with a certain website or try to sign a transaction

### Expected Results

I can sign the transaction.

### Actual Results

Nothing, the wallet is white and empty.

**Comment by kieranroneill** [comment]
Hey @ViSTiE thanks for reporting this. Is this happening on the Voi website, or is it any website that Kibisis tries to connect to?

**Comment by ViSTiE** [comment]
> Hey @ViSTiE thanks for reporting this. Is this happening on the Voi website, or is it any website that Kibisis tries to connect to?

It's actually on the Voi website. So there are two problems I encounter:

1. Installing Kibisis in the Brave browser works, but I can't set a password at the start. Every password I enter is too weak, the green bar beneath the password box doesn't move. 
2. Installing Kibisis in Chrome and Edge works, I can set a password and import my wallet. But connecting Kibisis to the Voi rewards account website doesn't work. The wallet is called, but it's empty and white. When I open the wallet in my browser, I can see everything (balance, tokens, etc.), so I leave it open. Then I try to connect the wallet on my Voi accounts page again and this time, another wallet instance opens, but this one is empty and white and shows this bug.

**Comment by kieranroneill** [comment]
I published a new release today (about 20 minutes ago :sweat_smile:) (v1.18.1) that should specifically address the first issue. There was a regression bug that stopped new passwords from having their complexity scored (it was permanently scored low regardless of the complexity). 

As for the second problem, I will investigate today, as I think another user reported a similar issue on Voi's Discord.

**Comment by ViSTiE** [comment]
> I published a new release today (about 20 minutes ago 😅 - v1.18.1) that should specifically address the first issue. There was a regression bug that stopped new passwords from having their complexity scored (it was permanently scored low regardless of the complexity).
> 
> As for the second problem, I will investigate today, as I think another user reported a similar issue on Voi's Discord.

Thanks, I installed the update, it works 👍

**Comment by kieranroneill** [comment]
✅ Fixed in #292
